name: Docker Release

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the hello-docker Docker image
        run: |
           docker build . --tag ghcr.io/tilation/nginx-pterodactyl-egg:latest
           docker run ghcr.io/tilation/nginx-pterodactyl-egg:latest
           docker push ghcr.io/tilation/nginx-pterodactyl-egg:latest
